#if !defined(KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED)
#define KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED

#include "includes/define.h"
#include "includes/kratos_application.h"
#include "includes/variables.h"
#include "includes/mat_variables.h"

namespace Kratos
{
typedef array_1d<double, 3> Vector3;

    // Miscelaneous
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_1)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_2)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_3)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, int, NUMBER_REDUCED_MODES)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Matrix, REDUCED_MODES_MATRIX)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Vector, REDUCED_MODES_WEIGHTS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Vector, INTEGRATION_POINT_WEIGHT)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_4)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_5)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_6)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, INELASTIC_FLAG)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Node<3>::Pointer, LAGRANGE_MULTIPLIER_NODE)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, GAUSS_WEIGHTS)

    // Damage constitutive model
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, ISOTROPIC_DAMAGE_MODULUS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, INFINITY_YIELD_STRESS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, int, FLOW_RULE_IS_TRACTION_ONLY)

    // Plasticity constitutive model (variables defined in the core)
    //KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, INFINITY_HARDENING_MODULUS)
    //KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, HARDENING_EXPONENT)
    //KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, REFERENCE_HARDENING_MODULUS)
    //KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, ISOTROPIC_HARDENING_MODULUS)

}

#endif /* KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED */
