#if !defined(KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_SOLID_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED

// System includes
// External includes
// Project includes
#include "includes/define.h"
#include "includes/kratos_application.h"
#include "includes/variables.h"

namespace Kratos {
    ///@name Type Definitions
    typedef array_1d<double,3> Vector3;
    typedef array_1d<double,6> Vector6;
    
    //Define Variables
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, ISOTROPIC_DAMAGE_MODULUS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, INFINITY_YIELD_STRESS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, int, FLOW_RULE_IS_TRACTION_ONLY)
//    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( RVE_FULL_DISPLACEMENT )
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, REFERENCE_TEMPERATURE)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, DETERMINANT_F)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGIAN_DOF_1)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGIAN_DOF_2)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGIAN_DOF_3)
}

#endif	/* KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED */
