#include "multiscale_rom_application_variables.h"

namespace Kratos
{
typedef array_1d<double, 3> Vector3;

    // Miscelaneous
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_1)
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_2)
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_3)
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_4)
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_5)
    KRATOS_CREATE_VARIABLE(double, LAGRANGE_MULTIPLIER_6)
    KRATOS_CREATE_VARIABLE(int, NUMBER_REDUCED_MODES)
    KRATOS_CREATE_VARIABLE(Matrix, REDUCED_MODES_MATRIX)
    KRATOS_CREATE_VARIABLE(Vector, REDUCED_MODES_WEIGHTS)
    KRATOS_CREATE_VARIABLE(Vector, INTEGRATION_POINT_WEIGHT)
    KRATOS_CREATE_VARIABLE(Node<3>::Pointer, LAGRANGE_MULTIPLIER_NODE)

    // Damage
    KRATOS_CREATE_VARIABLE(double, ISOTROPIC_DAMAGE_MODULUS)
    KRATOS_CREATE_VARIABLE(double, INFINITY_YIELD_STRESS)
    KRATOS_CREATE_VARIABLE(int, FLOW_RULE_IS_TRACTION_ONLY)
}
