#if !defined(KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_SOLID_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED

#include "includes/define.h"
#include "includes/kratos_application.h"
#include "includes/variables.h"

namespace Kratos {
    ///@name Type Definitions
    typedef array_1d<double,3> Vector3;
    typedef array_1d<double,6> Vector6;
    
    //Define Variables
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, ISOTROPIC_DAMAGE_MODULUS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, INFINITY_YIELD_STRESS)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, int, FLOW_RULE_IS_TRACTION_ONLY)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_1)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_2)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_3)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_4)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_5)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, double, LAGRANGE_MULTIPLIER_6)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Vector, INITIAL_STRAIN_VECTOR)
    KRATOS_DEFINE_APPLICATION_VARIABLE(MULTISCALE_ROM_APPLICATION, Node<3>::Pointer, LAGRANGE_MULTIPLIER_NODE)

}

#endif	/* KRATOS_MULTISCALE_ROM_APPLICATION_VARIABLES_H_INCLUDED */
